---
- name: Install nginx
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: yes

    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true